server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/search
        - id: index-route # 同步请求配置路由，跳转到首页
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com
        - id: index-route2 # 异步请求配置路由，通过ajax请求加载数据
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-service # 异步请求配置路由，通过ajax请求加载数据
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com